REM @echo OFF
setlocal enabledelayedexpansion enableextensions

if not exist "build\" mkdir "build\"
nasm -f win64 src\main.asm     -i src\ -o build\main.obj
nasm -f win64 src\scratch.asm  -i src\ -o build\scratch.obj
nasm -f win64 src\utils.asm    -i src\ -o build\utils.obj

nasm -f win64 src\days\day1.asm -i src\ -o build\day1.obj
nasm -f win64 src\days\day2.asm -i src\ -o build\day2.obj
nasm -f win64 src\days\day3.asm -i src\ -o build\day3.obj
nasm -f win64 src\days\day4.asm -i src\ -o build\day4.obj

nasm -f win64 src\os\windows.asm -i src\ -o build\windows.obj


REM set objects="build\main.obj build\scratch.obj build\utils.obj build\day1.obj build\day2.obj build\day3.obj build\day4.obj build\windows.obj"
set objects=
for %%x in (.\build\*.obj) do set objects=!objects! %%x

REM Generated by the MINGW dlltool:
set libkernel32="res/kernel32.lib"

REM Official MS kernel32.Lib. The path may need to be adjusted if you prefer to use this one:
REM set libkernel32="Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\kernel32.Lib"

link %objects% %libkernel32% /entry:main /out:build/aoc.exe 
build\aoc.exe
